# Configurações gerais da página.
# Nas tag abaixo, poderá ser configurado o título do site, uma descrição para SEO, sudpasta do site e URL principal.
title: Wiki Performance
description: Repositório de documentação para a equipe de Performance da Caixa.
baseurl: "/faqperformance"
url: "https://rafaelvie.github.io"

# Tema remoto para a página.
remote_theme: just-the-docs/just-the-docs

# Habilitar ou desabilitar âncoras de cabeçalho 
heading_anchors: true

# Faz os links Aux abrirem em uma nova aba. O padrão é falso 
aux_links_new_tab: true

# Ordem de classificação para links de navegação 
# nav_sort: case_insensitive # padrão, equivalente a nil 
nav_sort: case_sensitive # Letras maiúsculas classificadas antes das minúsculas 

# Link Voltar ao topo
back_to_top: true
back_to_top_text: "Voltar ao topo"

footer_content: "Copyright &copy; 2022 Equipe de Desempenho e Performance. Desenvolvido para <a href=\"https://caixa.gov.br\">Caixa Econômica Federal.</a>"
