# Configurações gerais da página.
# Nas tag abaixo, poderá ser configurado o título do site, uma descrição para SEO, sudpasta do site e URL principal.
title: Wiki Performance
description: Repositório de documentação para a equipe de Performance da Caixa.
baseurl: "/faqperformance"
url: "https://rafaelvie.github.io"

# Tema remoto para a página.
remote_theme: just-the-docs/just-the-docs
